darraghoriordan/eslint-plugin-nestjs-typed

README.md
src/configs/noSwagger.ts
src/configs/recommended.ts
src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.test-data.ts
src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.test.ts
src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.ts
src/rules/index.ts

BREAKING CHANGE: renames a rule

feat!: Renames api-method-should-specify-api-operation rule to api-method-should-specify-api-response

---

src/rules/apiPropertyReturningArrayShouldSetArray/apiPropertyReturningArrayShouldSetArray.test.ts
src/rules/apiPropertyReturningArrayShouldSetArray/apiPropertyReturningArrayShouldSetArray.ts

This PR fixes a missing null-check causing crashes of ESLint.
The error occurs when trying to lint a class containg an infered field type.
In the below example, the explicit type `boolean` is optional if the default value is set to `false`:
```ts
class TestClass {
@Expose()
@ApiPropertyOptional()
thisIsABooleanProp = false;
}
```

fix: missing null-check in `apiPropertyReturningArrayShouldSetArray`

---

src/rules/validate-non-primitves-needs-type-decorator/validateNonPrimitiveNeedsDecorators.ts

Love this repo — thanks!
I noticed my console was getting flooded with `deccc` during linting from  the `validate-non-primitves-needs-type-decorator` rule. Looks like an unnecessary `console.log` statement used for debugging slipped through the net.
This tiny PR removes it.

fix: Remove noisy console.log

---

src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts
src/utils/typedTokenHelpers.ts

Similar to `@IsEnum`, `@IsObject` should also be ignored from requiring explicit transforms. 
Closes #41 
Created a separate function to detect @IsObject decorators similar to IsEnum. Alternatively, we could combine this into one function so that only one conditional check needs to execute. 
Perhaps name it something like areIgnoredDecorators

fix: detect `isObject` decorator usage

---

src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts

This PR serves to add autofix suggestions for @Type() decorators by suggestion the @Type decorator along with inferred type to add in the.
The autofix suggestion should only show up if type are neither union or intersection types
Got the idea from #36, and had done something similar for a custom eslint plugin in my company. Did an early proof-of-concept along with some test cases.
Will clean up the code if this is a feature you think is worth having!

feat: autofix suggestions for validateNonPrimitiveNeedsDecorators

---

src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitvesNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts

Closes #39 
Thanks again for creating this set of plugins. We're currently using the `validateNonPrimitiveNeedsDecorators` rule and realise that the linter was throwing false positives for matches in #39
This happens because we are not tracking `null` as a primitive type.
Although it might not make sense to send a `null` in the request dto, we were combining both ORM decorators (typeorm) and request validators in our project. As such, a class property could be null for nullable database columns.
Tested and verified that existing logic does not break, and new use case is supported!

fix: detect null primitive types

---

package.json

It should be `--colors`. Added missing s.
https://jestjs.io/docs/cli#--colors

fix: typo in jest CLI flag(--colors)

---

README.md
src/configs/recommended.ts
src/rules/apiMethodsShouldBeGuarded/apiMethodsShouldBeGuarded.test.ts
src/rules/apiMethodsShouldBeGuarded/apiMethodsShouldBeGuarded.ts
src/rules/index.ts

Adds a lint to ensure that any endpoint method has a `@UseGuards` decorator, either at the method or class level.
It's super useful for ensuring correct endpoints have appropriate authentication + authorisation, but it's useless for an open API. 
I've added it to Recommended for testing, but I don't think it really belongs there. Could go into Recommended in an "off" state, allowing people to override it?
It doesn't yet have docs - I'll add those as soon as I know where it's going (i.e. that this will be accepted as a PR in some state)

feat: Add UseGuards detection to controller methods

---

src/configs/noSwagger.ts
src/configs/recommended.ts
src/rules/apiMethodsShouldSpecifyApiOperation/apiMethodsShouldSpecifyApiOperation.test.ts
src/rules/apiMethodsShouldSpecifyApiOperation/apiMethodsShouldSpecifyApiOperation.ts
src/rules/index.ts

I discovered in issue history that there was this rule once, but it checked ApiResponses, and was renamed
Due to need to cover the whole api with ApiOperations (#52), I present the actual rule for doing this.

feat: add api-method-should-specify-api-operation rule

---

src/docs/rules/all-properties-have-explicit-defined.md
src/rules/allPropertiesHaveExplicitDefined/allPropertiesHaveExplicitDefined.spec.ts
src/rules/allPropertiesHaveExplicitDefined/allPropertiesHaveExplicitDefined.ts

Issue #115 asked for @ValidateIf to be handled in the same manner as @IsOptional. 
This PR implements the requested feature. In addition to adding support for @ValidateIf, it introduces checks for conflicting decorators for all the combinations.

feat: :sparkles: Handle @ValidateIf like @IsOptional

---

src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts

Fixes #185.
Treats literal types, e.g. literal strings or literal numbers, as primitives for the purposes of this rule. Properties whose type are a literal type, or are union types containing literal types, no longer trigger the need for `@Type` decorator.
Includes a couple of test cases that used to fail.

fix: Treat literals like primitives in validated-non-primitive-property-needs-type-decorator

---

README.md

- Removed the `validation-pipe-should-forbid-unknown` rule listing, since that apparently does not exist
- Added the `should-specify-forbid-unknown-values` rule that was missing
- Updated the `api-method-should-specify-api-response` rule to correctly reflect what the recommendation file contains
- This will resolve my issues #186
- Now using ✅ and ❌ emojis instead of `Y` and `N`
- Also a minor spelling fix! `Awsome` => `Awesome`

docs: Update rule recommendations list in readme

---

src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts

This should address #184 
It simply adds `unknown`, `any`, and `object` to the list of "primitives" for this rule to ignore.  
I also added tests to check for the `unknown[]` and `Array<unknown>` syntaxes since in my project these would fail in different ways as I was trying to figure this out.

fix: ignore arrays of `unknown`, `any`, and `object` to fix #184

---

package.json
yarn.lock

This PR updates the `@typescript-eslint` monorepo to `v8.21.0`, and unpins the `@typescript-eslint/scope-manager` and `@typescript-eslint/utils` dependencies.
This change reduces the potential for multiple versions of `@typescript-eslint` packages being installed and decrements bloat in `yarn.lock` files, it also prevents issues that normally happen when multiple versions of the same dependency are installed in a project.
Given the current configuration, we are unable to update (to) any dependencies that use `typescript-eslint@8.21.0` as the latest version of this packages requires exactly version `8.20.0`, causing multiple versions of  `@typescript-eslint` packages to be installed. While some packages get updated quite regularly ans sometimes between hours of pinned dependencies, this is …

fix(deps): unpin @typescript-eslint dependencies & update them to v8.21.0

---

eslint.config.mjs

- Fixes hardcoded reference to user folder
- Fixes eslint config itself getting linted and thereby throwing an error like "this file is not in the tsconfig, but is being linted" or sth

build: fix eslint config

---

src/rules/paramDecoratorNameMatchesRouteParam/paramDecoratorNameMatchesRouteParam.test.ts
src/rules/paramDecoratorNameMatchesRouteParam/paramDecoratorNameMatchesRouteParam.ts

Server-Sent Events (SSE) is a server push technology enabling a client to receive automatic updates from a server via HTTP connection.
In NestJS, `@Sse()` decorator is similar to normal HTTP decorators like `@Get()` or `Post()`, that it supports path variables. This PR provides support for `@Sse()` decorator under `param-decorator-name-matches-route-param` rule.

feat: add support for Sse decorator

---

src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.test.ts
src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.ts
src/rules/controllerDecoratedHasApiTags/controllerDecoratedHasApiTags.test.ts
src/rules/controllerDecoratedHasApiTags/controllerDecoratedHasApiTags.ts

This PR modifies two rules to respect the `@ApiExcludeController()` decorator from `@nestjs/swagger`:
1. `controllers-should-supply-api-tags`
2. `api-method-should-specify-api-response`
Currently, these rules require API documentation decorators even for controllers that are explicitly excluded from Swagger documentation using `@ApiExcludeController()`. This forces developers to either:
- Add unnecessary API documentation decorators to excluded controllers
- Use `eslint-disable` comments to suppress the rules
- Modified `controllers-should-supply-api-tags` to skip the `@ApiTags()` requirement for controllers with `@ApiExcludeController()`
- Modified `api-method-should-specify-api-response` to skip the API response decorator requirement for methods in controllers with …

feat: respect ApiExcludeController decorator in api response and tags rules

---

src/rules/apiMethodsShouldSpecifyApiResponse/apiMethodsShouldSpecifyApiResponse.ts

This PR setting @HealthCheck() decorator as ApiResponse decorator.
Issue: https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/issues/270

fix(renovate):  HealthCheck as api response decorator

---

src/docs/rules/param-decorator-name-matches-route-param.md
src/rules/paramDecoratorNameMatchesRouteParam/paramDecoratorNameMatchesRouteParam.test.ts
src/rules/paramDecoratorNameMatchesRouteParam/paramDecoratorNameMatchesRouteParam.ts

Resolves Issue #296 
Now you can use variables or templates in a `@Controller` and still be alerted to mismatches between route param names

feat: Add a `shouldCheckController` option to the `param-decorator-name-matches-route-param` rule

---

src/docs/rules/validated-non-primitive-property-needs-type-decorator.md
src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.test.ts
src/rules/validateNonPrimitiveNeedsTypeDecorator/validateNonPrimitiveNeedsDecorators.ts

This addresses #289 where the `validated-non-primitive-property-needs-type-decorator` rule would crash when it encountered an array with an inferred type.
Very little code changes needed, but I also added some minor spelling/formatting changes for the related docs.

fix: #289 for `validated-non-primitive-property-needs-type-decorator` rule
